import type { Metadata } from "next";
import "@/app/global.css"; // Sebaiknya CSS global diimpor di sini

export const metadata: Metadata = {
  title: "Ruang Trading",
  description: "Generated by create next app",
  icons: {
    icon: '/logo-rt.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="font-sans">
        {/* Children di sini akan menjadi salah satu dari:
            - (public) layout (dengan Navbar)
            - (admin) layout (dengan Sidebar)
            - (auth) layout (yang kosong ini)
        */}
        {children}
      </body>
    </html>
  );
}